{% set name = "chroma-hnswlib" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chroma-hnswlib-{{ version }}.tar.gz
  sha256: 87c6a0ced9e52ac7c8ca01ded25bb70c4a7f63f5871181eb18bea9111ce786c4
  patches:
    - 0001-Check-before-removing-march-native.patch

build:
  number: 1
  script:
    # HNSWLIB_NO_NATIVE is set to build without "--march=native"
    - export HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [unix]
    - set HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [win]

requirements:
  # see https://github.com/conda-forge/hnswlib-feedstock/blob/main/recipe/meta.yaml
  build:
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11 >=2.0
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - hnswlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chroma-core/hnswlib
  summary: Chromas fork of hnswlib
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
