{% set name = "chroma-hnswlib" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4dce282543039681160259d29fcde6151cc9106c6461e0485f57cdccd83059b7

build:
  number: 1
  script:
    # HNSWLIB_NO_NATIVE is set to build without "--march=native"
    - export HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [unix]
    - set HNSWLIB_NO_NATIVE=1 && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [win]

requirements:
  # see https://github.com/conda-forge/hnswlib-feedstock/blob/main/recipe/meta.yaml
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11 >=2.0
    - numpy
  run:
    - python

test:
  imports:
    - hnswlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chroma-core/hnswlib
  summary: Chromas fork of hnswlib
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
